### ISSUE TITLE
Service crash on incoming phone call

### ISSUE THREAD

**Issue by MetalGearSolidNerd** [AmazMod/AmazMod#377]
Amazmod service v1843
Amazmod app v1.1

After updating to latest Amazmod on beta channel incoming phone calls result in crash of Amazmod service on the watch. This behaviour was not seen with v1.0.65 + 1702.

Selected notification apps do not contain any Telephone/Phone app.

After crash the only way to re-establish communication is to go to Amazmod widget which causes it it to refresh and go to first position and then force close Amazmod app on phone and then re-open. This probably does not happen with all calls (need to confirm) and may have something to do with phone number format. Although it clearly worked well with previous version.

**Comment by lfom** [comment]
Weird. Thanks for the good report. If you can find a way to reproduce the crash, please report it step by step. If not, a logcat may help. But I think that it is already fixed in the current beta version (1.1.3) and no one ever reported such problem...

**Comment by MetalGearSolidNerd** [comment]
Thank you for your response. I will try to get a logcat.

For beta version (1.1.3), is it the one currently released on Play Store. I am enrolled in the beta program but Amazmod version is still shown as 1.1.0.

**Comment by diotto** [comment]
@MetalGearSolidNerd , version 1.1.3 is currently available as Public release (together with service version 1880). Is it workign now ?

**Comment by MetalGearSolidNerd** [comment]
Kind of working.

When I receive a call now (v1.1.3 + 1880), I get the call notfication via Amazfit but then if I unlock the watch I also see "Welcome to Amazmod" message. Seems like Amazmod restarted.

Not a big pain though, since Amazmod app on phone remains connected so I continue to receive notifications. Previously I had to force restart watch app + phone app for it to work again.

**Comment by diotto** [comment]
@MetalGearSolidNerd this "Wecome to Amazmod" notification should not appear.
Is Amazmod Phone app and Service communicationg well ? In Phone main screen can you see watch version information and the status as "Connected" ?
I suggest also you to try the test notifications from About screen of amazmod phone app.
Thanks for your information.

**Comment by GreatApo** [comment]
Issue continues at: https://github.com/AmazMod/AmazMod/issues/400

**Comment by fcaronte** [comment]
I think is not the same, I remember that on my Samsung if I enable "phone" app to notification list its start crash when receive call, removing it fix the problem and receive correctly call notification by default system
